<a href="https://colab.research.google.com/github/ShaafPlayz/PyTorch-MyPlayGround/blob/main/00_Shaaf_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introductin to tensors

Creating Tensors

Pytorch tensors are created using torch.Tensor()


In [ ]:
# scalar
import torch
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()
#Get tensor bacak as Python int

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:

TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8233, 0.0566, 0.7415, 0.9133],
        [0.1228, 0.3964, 0.3296, 0.5283],
        [0.8005, 0.9183, 0.6583, 0.6554]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start =0, end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,  # what datatpye is the tensor (float16 or float32)
                               device="cuda", # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [ ]:
yes = float_16_tensor * float_32_tensor
yes.dtype

torch.float32

### Getting information from Tensor (tensor attributes)

1. datatype -> tensor.dtype
2. shape -> tensor.shape
3. device -> tensor.device

In [ ]:
# Create tensor

some_tensor = torch.rand(3,4)
some_tensor = some_tensor.type(torch.float16)

In [ ]:
# Find out details aabout some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3767, 0.2303, 0.0466, 0.6416],
        [0.7793, 0.8843, 0.7241, 0.2214],
        [0.7935, 0.6123, 0.1196, 0.8516]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Try out PyTorch in-buily functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**


In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value =0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.48 ms, sys: 0 ns, total: 2.48 ms
Wall time: 3.86 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.29 ms, sys: 55 µs, total: 1.35 ms
Wall time: 1.11 ms


tensor(14)

### One of the most common errors in deep learning is shape errors

In [ ]:
shaaf1 = torch.zeros(2,3)
shaaf2 = torch.zeros(3,2)
shaaf1

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
shaaf2

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B)
# torch.matmul(tensor_A, tensor_B)


In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

## Finding the min, max mean, sum, etc (tensor aggregation)

In [ ]:
#Create tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# find the man
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
# Note: the torch.mean() function requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack and hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Creating a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Adding a dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing the view - z now shares memeory with x but shows that tensor in a different view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0 ] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# torch.unsqueeze - adds a single dimension to a target tensor at a specific dim
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# torch.permute - rearranges the dim of a target tensor in a speicfied  order
x_original = torch.rand(size =(224, 224, 3)) # [height, width, color_channels]
x_original[0,0,0] = 69
# Permute the original tensor to rearrange th axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_permuted[0, 0, 0]

tensor(69.)

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [ ]:
# Creating a tensor
import torch
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Indexing on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Indexing on middle bracket (dim=1)
x[0,0]
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Lets index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# Using ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st, but index only 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x.shape

torch.Size([1, 3, 3])

In [ ]:
# Get all values of 1st dim, but index 1 of 1st & 2nd dim
x[:, 1, 1] # we get the square brackets because we have selected all of the values of the first index

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & Numpy

* Data in NumPy, want in PyTorch Tensor -> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy -> 'torch.Tensor.numpy()'

In [ ]:
# NumPy array to Tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor # default numpy dtype is float64

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Change the value of array, what will this do to 'tensor'??
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, to see what happens to 'numpy_tensor'????
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# either dont share memory when converted

## Reproduceability (Taking the random out of random)

in short how a neural network learns:

`start with random numbers -> tensor operations -> change the random numbers to try and make them better representations of the data -> tensor operations -> change the random numbers -> repeat -> repeat.......`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6531, 0.8904, 0.3708, 0.2596],
        [0.7478, 0.3079, 0.4962, 0.2928],
        [0.0297, 0.2383, 0.1093, 0.8284]])
tensor([[0.0419, 0.5478, 0.2771, 0.2551],
        [0.9254, 0.3625, 0.0789, 0.0674],
        [0.2591, 0.6900, 0.1932, 0.4130]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Lets make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 117
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3 ,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.5612, 0.3072, 0.6293, 0.0368],
        [0.1262, 0.7612, 0.6377, 0.4232],
        [0.7296, 0.3673, 0.4811, 0.3588]])
tensor([[0.5612, 0.3072, 0.6293, 0.0368],
        [0.1262, 0.7612, 0.6377, 0.4232],
        [0.7296, 0.3673, 0.4811, 0.3588]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPU

In [ ]:
 !nvidia-smi

Wed Jan 15 01:51:07 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Check GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# setup agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on GPU

because gpu runs tensors/models faster

In [ ]:
# New Tensor
tensor = torch.tensor([1,2,3], device = "cpu")

# Tensor not on GPU
tensor.device

device(type='cpu')

In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix this issue, we move tensor to CPU from GPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.numpy()

array([1, 2, 3])